replicaCount: 1

app:
  repository: evoluticstech/nas-service-dev
  tag: 39
  port: 8755
env_secrets:
  enabled: false
  name: evolutics
imagecredentials:
  enabled: true
  name: ets-docker
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1000M
  url: nas-service.evoluticstech.com
  path: /hello-sa
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
extraenv:
  enabled: false
  NAME: hello
  ENV: prod
liveness:
  enabled: false
  config:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
readiness:
  enabled: false
  config:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
issuer:
  enabled: false
  name: letsencrypt
  ingressClass: nginx
