replicaCount: 1

app:
  repository: evoluticstech/core-event-service
  tag: 5
  port: 8012

env_secrets:
  enabled: false
  name: evolutics

imagecredentials:
  enabled: true
  name: nas-prod

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: ets-test4.evoluticstech.com

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  
volumes: []
volumeMounts: []

extraenv:
  enabled: false
  NAME: hello
  ENV: prod

liveness:
  enabled: false
  config:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10

readiness:
  enabled: false
  config:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10


issuer:
  enabled: false
  name: letsencrypt
  ingressClass: nginx
